version: 2

sources:
  - name: raw_open_air_quality
    description: "This source contains the raw air quality data from the Open Air Quality project."
    database: air_quality_test #or gcp project name
    schema: raw_openaq # or gcp dataset name
    tables:
        - name: raw_openaq_measurements
          description: "This table contains the raw air quality measurements from the Open Air Quality project."
